on:
    schedule:
 #    - cron: '5 6 * * 5'
    workflow_dispatch:

name: evacuation tables

jobs:
  render:
    name: Pull latest evacuations, update tables
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v1
  
  
  
        env:
          GOOGLESHEETS4_PASSWORD: ${{ secrets.XXXXX }}