on:
    schedule:
     - cron: '5 6 * * 5'
    workflow_dispatch:

name: evacuation tables

env:
  GOOGLE_JSON: ${{ secrets.GOOGLE_JSON }}
  GS_API: ${{ secrets.GS_API }}
  
jobs:
  render:
    name: Pull latest evacuations, update tables
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v1
      - name: Set up pandoc for Rmd docs
        uses: r-lib/actions/setup-pandoc@v1
      - name: Install gdal
        run: |
          brew install gdal
      - name: Install dependencies and packages
        run: Rscript -e 'install.packages(c("tidyverse","janitor","readxl","jsonlite","googlesheets4","googledrive","htmlwidgets", "htmltools","data.table","fontawesome"))'
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "google_service_account.json"
          json: ${{ secrets.GOOGLE_JSON }}
      - run: git config --global user.email "39309451+lindseyf96@users.noreply.github.com" && git config --global user.name "lindseyf96" && git add . && git add --force google_service_account.json && git status && git commit -a -m "service account credentials"
      - name: Create file
        run: cat google-services.json | base64
      - name: Putting data
        env:
            DATA: ${{ secrets.GOOGLE_JSON }}
        run: echo $DATA > google-services.json
      - name: Get data from google sheets
        run: Rscript scripts/github_evac_code.R
      - name: Commit results
        run: |
          git add -A
          git commit -m 'Update evac tables' || echo "No changes"
          git push origin || echo "No changes to commit"
